# Generated by Django 2.1.7 on 2020-07-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=100)),
                ('doc', models.FileField(upload_to='docs')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.CharField(max_length=2)),
            ],
        ),
    ]
